#服务端口
server:
  port: 8889
  #服务名
spring:
  application:
   name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev

  #阿里云 OSS
  #不同的服务器，地址不同
aliyun:
  oss:
    file:
     endPoint: oss-cn-beijing.aliyuncs.com
     keyId: LTAIarJf4FSjmhWR
     keySecret: lra8TPq85ovDgs9lGTuBChi3FQAdto
  #bucket可以在控制台创建，也可以使用java代码创建
     bucketName: edu-20201020